### ISSUE TITLE
ES5 support

### ISSUE THREAD

**Issue by friendOfOurs** [uhlryk/react-dynamic-number#19]
I get multiple errors when using the module as follows: 
`var DynamicNumer = require('react-dynamic-number')`

I guess the reason is that module doesn't work with es5, commonjs?

Cheers!

**Comment by uhlryk** [comment]
Hi
Thank you for your feedback.
Please write here those errors.
I haven't tested it with ES5 (I use them with ES6), but I think, that It should work with ES5.

**Comment by stormcleric** [comment]
I'm sure this fill have been already solved but the key to ES5 is:
`var DynamicNumber = require('react-dynamic-number').default;`

**Comment by uhlryk** [comment]
Thanks, that you point it out. I will add section FAQ in documentation and write it.
