### ISSUE TITLE
Add id value

### ISSUE THREAD

**Issue by n-amabile-brightplan** [uhlryk/react-dynamic-number#20]
Hey, can you please add an id to the input field? Even if I add it to the DynamicNumber element, when I inspect the code, those values are not there.
For example:

```
<DynamicNumber
  thousand={','}
  integer={7}
  type='number'
  min={0}
  id='someIdHere'
  ref='someRefHere'
  onChange={this.valueChange}
  value={this.state.something} />
```

Generated input:
`<input type='text' class='some-css-class' value='something'>`

Thanks!

**Comment by uhlryk** [comment]
Hey
Yes, sure. You have right that this is important.
Now it should work (also for other html attributes).
Please confirm if now it works.

**Comment by n-amabile-brightplan** [comment]
Apparently `onChange` is not being called anymore, all the others like `onBlur` and `onFocus` work fine

**Comment by uhlryk** [comment]
Please look at example code https://github.com/uhlryk/react-dynamic-number/blob/master/example/app.jsx
There is in use onChange event to show how model looks like.
You can run example page here http://htmlpreview.github.io/?https://github.com/uhlryk/react-dynamic-number/blob/master/example/index.html

Maybe you may provide example where it doesn't work or help me to reproduce it. Then I will fix it. Maybe there is some error in console?

**Comment by n-amabile-brightplan** [comment]
Ok, removing type='number' solved the issue, thanks very much for your fast responses!
