### ISSUE TITLE
move react to peerDependencies

### ISSUE THREAD

**Issue by mixtur** [uhlryk/react-dynamic-number#25]
Can you please move react to devDependencies or peerDependencies.
Otherwise react is included twice in any application that uses your component and version of React different than yours.
Another possible option is to make react dependency more loose. Like '>= 0.14.5' instead of '^0.14.5'

**Comment by uhlryk** [comment]
Thanks that you pointed this.
I moved react to both (peerDependency because it should work in host application, and devDependency because examples need react to build), and also loose versions.
Please give me feedback if it is ok now

**Comment by mixtur** [comment]
Yes now it is ok. And it looks like https://github.com/uhlryk/react-dynamic-number/issues/23 is also got fixed somehow.
