### ISSUE TITLE
PlaceHolder Values

### ISSUE THREAD

**Issue by jshewaski** [uhlryk/react-dynamic-number#26]
The placeholder value seems to be set at the value 0 no matter what is placed in this element. Is there some way to make this value empty so the initial value is not 0.

**Comment by uhlryk** [comment]
Thanks, I will add placeholder prop.

**Comment by uhlryk** [comment]
Hey
I checked, and placeholder works correctly. Value by default is equal 0 therefore it shows 0 (zero is no placeholder it is value).
To make it works: add placeholder attribute with string, set value="". Now at the beginning value is empty and it will show you placeholder. 
I will close this ticket. If my solution doesnt work for you, please paste here problematic code and I will help you figure it out
