### ISSUE TITLE
Refs Problem

### ISSUE THREAD

**Issue by jshewaski** [uhlryk/react-dynamic-number#27]
Using refs seemed to work fine in our DEV environment set in the react-router. Though when put into production mode it no longer recognized this element component as a valid react component and threw an error due to the ref being added. 

The error read: 
Minified React error #120; visit http://facebook.gitbhub.io/react/docs/error-decoder.html?invariant=120 for the full message or use the non-minified dev environment for full errors......

**Comment by uhlryk** [comment]
In this component I don't use refs at all. In addition this component don't have any dependencies (It has only react and react-dom as peer dependencies - therefore it shouldn't be fault of any dependent).
Maybe you could isolate error and show this code to allow me reproduce problem - then I will for sure fix it
