### ISSUE TITLE
Add focus support

### ISSUE THREAD

**Issue by posty72** [uhlryk/react-dynamic-number#28]
There needs to be a `focus` method on the component so parent elements can focus on the input.

**Comment by uhlryk** [comment]
Thank you for you patience. Focus is implemented. It works like normal input:
You take ref from component. Then in componentDidUpdate() call focus on this ref.
If you will encounter any problems I will try help you. For now I close this ticket

**Comment by js562187** [comment]
Thanks for the update, also thanks for the help with the other issues! Keep up the good work.

**Comment by posty72** [comment]
Cheers for the update!

**Comment by sjain-mi9** [comment]
Can we have something like onFocus and onBlur props of type function, which invokes when the input is focused and blur?

**Comment by uhlryk** [comment]
Hey @sjain-mi9 in future please create new issue for features. This ticket is closed and almost I miss it.
OnFocus and onBlur are out of the box (any standard react synthetic event for input should work).
Example:
```
<DynamicNumber 
  onFocus={()=>console.log("onFocus")} 
  onBlur={()=>console.log("onBlur")} 
  className="form-control" 
  onChange={this.onChange.bind(this,0)} 
  separator={','} integer={5} fraction={5} 
/>
```

Now when you click input it will print in console "onFocus". When you click something else it will print "onBlur".
If you have more questions about it, please create new issue.

**Comment by sjain-mi9** [comment]
@uhlryk  Thank you very much.
