### ISSUE TITLE
React 16 Warning

### ISSUE THREAD

**Issue by iliesalex89** [uhlryk/react-dynamic-number#34]
Starting from react 16, I see that assigning values  to "this.state" in componentWillReceiveProps, will raise a warning which suggests to use ".setState".

Can you please update this in the next version? Thanks in advance

**Comment by uhlryk** [comment]
I merged @haydnhkim  PR. Should be fixed.

**Comment by haydnhkim** [comment]
@uhlryk Version 1.7.0 has not changed.
The release folder has not been updated.
Build and update, please. Thanks!

**Comment by uhlryk** [comment]
yes, sorry for that. Right now should be ok.  Please check v1.7.1
