### ISSUE TITLE
add thousand parameter

### ISSUE THREAD

**Issue by uhlryk** [uhlryk/react-dynamic-number#6]

**Comment by gdotdesign** [comment]
Hey, I would like to use this in a project, is there any ETA on adding this feature?

**Comment by uhlryk** [comment]
Hi
I will try to do it in the next few days

**Comment by uhlryk** [comment]
It should  work now. You can check fifth and sixth input in example page http://htmlpreview.github.io/?https://github.com/uhlryk/react-dynamic-number/blob/master/example/index.html

**Comment by gdotdesign** [comment]
Nice. Thank you!
